// ============================================================
// lib/pdf.ts — HTML→PDF via puppeteer-core + @sparticuz/chromium-min
// Vercel serverless compatible.
// ============================================================

export async function generatePDF(html: string): Promise<Buffer> {
  // Dynamic import to avoid bundling issues in Edge runtime
  const puppeteer = await import("puppeteer-core");

  let executablePath: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let chromiumArgs: string[];

  if (process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME) {
    // Serverless environment — use @sparticuz/chromium-min
    const chromium = await import("@sparticuz/chromium-min");
    executablePath = await chromium.default.executablePath(
      `https://github.com/Sparticuz/chromium/releases/download/v130.0.0/chromium-v130.0.0-pack.tar`
    );
    chromiumArgs = chromium.default.args;
  } else {
    // Local development — use system Chrome
    executablePath =
      process.platform === "win32"
        ? "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
        : process.platform === "darwin"
        ? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        : "/usr/bin/google-chrome";
    chromiumArgs = ["--no-sandbox", "--disable-setuid-sandbox"];
  }

  const browser = await puppeteer.default.launch({
    args: chromiumArgs,
    executablePath,
    headless: true,
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", right: "15mm", bottom: "20mm", left: "15mm" },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="width:100%;font-size:9px;color:#666;display:flex;justify-content:space-between;padding:0 15mm;">
          <span>Tata Play Competitor Intelligence — Confidential</span>
          <span class="date"></span>
        </div>`,
      footerTemplate: `
        <div style="width:100%;font-size:9px;color:#666;display:flex;justify-content:space-between;padding:0 15mm;">
          <span>Generated by Tata Play Intelligence Platform</span>
          <span><span class="pageNumber"></span> / <span class="totalPages"></span></span>
        </div>`,
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

/**
 * Build a print-optimized HTML document from a Markdown report string.
 * Uses inline CSS for WYSIWYG PDF output.
 */
export function buildReportHTML(markdownContent: string, title: string): string {
  // Simple markdown-to-HTML conversion for key elements
  const htmlBody = markdownContent
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11px; line-height: 1.6; color: #1a1a1a; }
    h1 { font-size: 20px; color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 6px; margin: 24px 0 12px; }
    h2 { font-size: 16px; color: #1a56db; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin: 20px 0 8px; }
    h3 { font-size: 13px; color: #374151; margin: 14px 0 6px; }
    p { margin: 6px 0; }
    ul { padding-left: 18px; margin: 6px 0; }
    li { margin: 3px 0; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; margin: 10px 0; }
    th { background: #1a56db; color: white; padding: 6px 8px; text-align: left; }
    td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
    tr:nth-child(even) { background: #f9fafb; }
    a { color: #1a56db; }
    .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; }
    .badge-high { background: #fee2e2; color: #991b1b; }
    .badge-medium { background: #fef3c7; color: #92400e; }
    .badge-low { background: #d1fae5; color: #065f46; }
    .page-break { page-break-before: always; }
    @media print { a { color: #1a56db; } }
  </style>
</head>
<body>
  <div style="text-align:center;margin-bottom:24px;">
    <h1 style="border:none;font-size:22px;">${title}</h1>
    <p style="color:#6b7280;">Generated: ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p>
  </div>
  <p>${htmlBody}</p>
</body>
</html>`;
}
